###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################

apiVersion: v1
kind: Service
metadata:
  annotations:
    # This is required as Kubernetes is not using the publishNotReadyAddresses spec setting below.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "dnsname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  # Kubernetes does nothing with this setting but it does use the "service.alpha.kubernetes.io/tolerate-unready-endpoints" annotation above.
  # publishNotReadyAddresses: true
  selector:
    app: {{ template "fullname" . }}
