## Metadata for Galera using MariaDB configuration
## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation

arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "Scheduling preference - amd64"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  
 
  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "Scheduling preference - ppc64le"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  
  
  # s390x:
  #   __metadata:
  #     name: "s390x"
  #     label: "Scheduling preference - s390x"
  #     description: "Architecture preference for target worker node."
  #     type: "string"
  #     immutable: false
  #     required: true
  #     options:
  #     - label: "0 - Do not use"
  #       value: "0 - Do not use"
  #     - label: "1 - Least preferred"
  #       value: "1 - Least preferred"
  #     - label: "2 - No preference"
  #       value: "2 - No preference"  
  #     - label: "3 - Most preferred"
  #       value: "3 - Most preferred"

## Image configuration metadata
image:
  __metadata:
    label: "Docker image configuration"
  repository:
    __metadata:
      name: "repository"
      label: "Docker repository"
      description: "Docker registry to pull image from."
      type: "string"
      immutable: "false"
      required: true
  tag:
    __metadata:
      name: "tag"
      label: "Tag"
      description: "Docker image tag to pull"
      type: "string"
      immutable: "false"
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"

# Database configuration
mariadb:
  __metadata:
    label: "Database configuration"
  rootPassword:
    __metadata:
      name: "rootPassword"
      label: "Root user password"
      description: "Password for the `root` user. Defaults to a generated value."
      type: "password"
      immutable: "false"
      required: false

  database:
    __metadata:
      name: "database"
      label: "New database name"
      description: "Name for new database to create."
      type: "string"
      immutable: "false"
      required: false

  user:
    __metadata:
      name: "user"
      label: "New user name"
      description: "Username of new user to create."
      type: "string"
      immutable: "false"
      required: false

  password:
    __metadata:
      name: "password"
      label: "New user password"
      description: "Password for the new user."
      type: "password"
      immutable: "false"
      required: false

  configMapName:
    __metadata:
      name: "configMapName"
      label: "ConfigMap name for my.cnf"
      description: "The name of a ConfigMap that contains a file my_extra.cnf with MariaDB configuration file content."
      type: "string"
      immutable: "false"
      required: false

replicas:
  __metadata:
    label: "Cluster configuration"
  replicaCount:
    __metadata:
      name: "replicaCount"
      label: "Replicas"
      description: "Number of replicas to deploy. Defaults to 3"
      type: "number"
      immutable: "false"
      required: true

## Persistence options
persistence:
  __metadata:
    label: "Data persistence configuration"
  enabled:
   __metadata:
      name: "enabled"
      label: "Enable persistence for this deployment"
      description: "Enables persistence for this deployment. Defaults to true. A persistent volume is required per replica if using ReadWriteOnce."
      type: "boolean"
      immutable: "false"
      required: true
  useDynamicProvisioning:
   __metadata:
      name: "useDynamicProvisioning"
      label: "Use dynamic provisioning for persistent volume"
      description: "If dynamic provisioning is available in the cluster this option will automatically provision the requested volume if set to true. Defaults to false."
      type: "boolean"
      immutable: "false"
      required: true

dataPVC:
  __metadata:
    label: "Persistent volume configuration"
  selector:
    __metadata:
      label: "Volume selector if not using dynamic provisioning"
    label:
      __metadata:
        name: "label"
        label: "Label to select the volume"
        type: "string"
        immutable: "false"
        required: false
    value:
      __metadata:
        name: "value"
        label: "Value of the label to select the volume"
        type: "string"
        immutable: "false"
        required: false
  storageClassName:
    __metadata:
      name: "storageClassName"
      label: "Storage class name"
      description: "Choose a specific storage class name. Defaults to the default storage class in the cluster."
      type: "string"
      immutable: "false"
      required: false
  size:
    __metadata:
      name: "size"
      label: "Size of the volume claim"
      description: "Defaults to 2Gi of storage request. Choose a different size of disk if needed."
      type: "string"
      immutable: "false"
      required: true

## Resource requests and limits configuration metadata
resources:
  __metadata:
    label: "Resource configuration"
  requests:
    cpu: 
      __metadata: 
        label: "CPU request"
        description: "The requested CPU"
        type: "string"
        required: true   
    memory: 
      __metadata: 
        label: "Memory request"
        description: "The memory request"
        type: "string"
        required: true   
  limits:
    cpu: 
      __metadata: 
        label: "CPU limit"
        description: "The CPU limit"
        type: "string"
        required: true   
    memory: 
      __metadata: 
        label: "Memory limit"
        description: "The memory limit"
        type: "string"
        required: true   

