# Default values for hyperledger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replica: 
  peers: 2
image:
  ca: fabric-membersrvc:latest
  peer: fabric-peer:latest
  pullPolicy: IfNotPresent
  
service:
  type: NodePort

resources: 
   limits:
    cpu: 200m
    memory: 512Mi
   requests:
    cpu: 200m
    memory: 512Mi
