{{-  $peers := int .Values.replica.peers | add1  -}}
{{- $cursor := . -}}
{{- range $i,$e := untilStep 1 $peers 1 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $cursor }}-regular-peer{{ $e }}
  labels:
    app: {{ template "fullname" $cursor }}-regular-peer{{ $e }}
    chart: {{ $cursor.Chart.Name }}-{{ $cursor.Chart.Version | replace "+" "_" }}
    release: {{ $cursor.Release.Name }}
    heritage: {{ $cursor.Release.Service }}
spec:
  type: {{ $cursor.Values.service.type }}
  ports:
    - port: 7050
      targetPort: 7050
      protocol: TCP
      name: "tcp-7050"
    - port: 7051
      targetPort: 7051
      protocol: TCP
      name: "tcp-7051"
    - port: 7053
      targetPort: 7053
      protocol: TCP
      name: "tcp-7053"      
  selector:
    app: {{ template "fullname" $cursor }}-regular-peer{{ $e }}
    release: {{ $cursor.Release.Name }}
{{- end -}}